#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Waiting for Elasticsearch on elasticsearch:9200..."
while ! nc -z elasticsearch 9200; do   
  sleep 1
done
echo "Elasticsearch is up and running!"

python manage.py migrate

python manage.py search_index --rebuild -f

exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
