services:
  docs:
    image: livecrowd_help_local_docs
    container_name: livecrowd_help_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./livecrowd_help:/app/livecrowd_help:z
    ports:
      - '9000:9000'
    command: /start-docs
