# Generated by Django 5.0.11 on 2025-01-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
