# Generated by Django 5.0.11 on 2025-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0003_event_mojo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_name',
            field=models.CharField(max_length=400),
        ),
    ]
