# Generated by Django 5.0.11 on 2025-01-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_name',
            field=models.CharField(default='Untitled Event', max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faqitems.venue'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(default='No answer available'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faqitems.event'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(default='No question provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='general', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='display_name',
            field=models.CharField(default='Unknown Venue', max_length=200),
        ),
    ]
