# Generated by Django 5.0.11 on 2025-02-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0007_alter_event_display_name_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='faqitems.venue'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='event',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='faqitems.event'),
        ),
    ]
