# Generated by Django 5.0.11 on 2025-02-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['display_name']},
        ),
    ]
