# Generated by Django 5.0.11 on 2025-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
