# Generated by Django 5.0.11 on 2025-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0002_faqitem_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
