# Generated by Django 5.0.11 on 2025-07-31 08:08

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0003_event_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='display_name'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['display_name']),
        ),
    ]
