# Generated by Django 5.0.11 on 2025-07-31 08:17

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0004_tag_slug_alter_event_slug_alter_faqitem_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='display_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='display_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name']),
        ),
    ]
