# Generated by Django 5.0.11 on 2025-07-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0005_alter_event_options_rename_display_name_event_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['updated_at']},
        ),
    ]
