# Generated by Django 5.0.11 on 2025-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0006_alter_event_options_alter_faqitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(max_length=4096),
        ),
    ]
