# Generated by Django 5.0.11 on 2025-07-31 14:54

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0007_alter_faqitem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['question']),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name']),
        ),
    ]
