# Generated by Django 5.0.11 on 2025-08-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0009_alter_event_name_alter_venue_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['updated_at'], 'permissions': [('add_with_csv', 'Add FAQ with CSV')]},
        ),
    ]
