# Generated by Django 5.0.11 on 2025-08-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqitems', '0010_alter_faqitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['updated_at'], 'permissions': [('add_faqitems_with_csv', 'Add FAQs with CSV')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('add_tags_with_csv', 'Add tags with CSV')]},
        ),
    ]
